version: "3.9"
services:
  cli:
    build: cli
    volumes:
      - ..:/workspaces/laravel

  fpm:
    build: fpm
    volumes:
      - ..:/workspaces/laravel
    user: 1000:1000

  nginx:
    # build: nginx
    image: nginx:1.21-alpine
    volumes:
      - ..:/workspaces/laravel
      - ./logs:/var/log/docker/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8010:80
    depends_on:
      - fpm

  # postgres:
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_DB: laravel
  #     POSTGRES_USER: root
  #     POSTGRES_HOST_AUTH_METHOD: trust
  
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example456
      MYSQL_DATABASE: laravel-app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  redis:
    image: redis:6.2-alpine

